#:kivy 1.0
<Warstwa>:
    canvas.before:
        Color:
            rgba: (240/255,201/255,1/255,1)
        Triangle:
            points: [int(2 * root.width), root.height, 0, int(0.9*root.height), 0, root.height]
    BoxLayout:

        id: layout
        
        orientation: "vertical"
        pos: 0, int(root.height/3)
        size: 400, 400

        padding: 60
        spacing: 10

        Button:
            text: "Powitanie"
            on_press: root.idle()
    FloatLayout:
        Button:
            size_hint: None, None
            pos: (root.width -self.width)/2, root.height - self.height - 10
            #pos_hint: {"center_x": 0.5, "center_y": 0.8 }
            size: 300, 100
            text: "Menu"
            on_release: context_menu.show(*app.root_window.mouse_pos)

        ContextMenu:
            id: context_menu
            visible: False
            cancel_handler_widget: layout
            ContextMenuTextItem:
                text: "Ule"
                #on_press: root.idle()
            ContextMenuTextItem:
                text: "Alerty"
                ContextMenu:
                    ContextMenuTextItem:
                        text: "Dziś"
                    ContextMenuTextItem:
                        text: "Arhiwum"