#:kivy 1.0
#:import ScreenManager kivy.uix.screenmanager.ScreenManager
#:import FadeTransition kivy.uix.screenmanager.FadeTransition




<Menu>:
    FloatLayout:
        #size: 500, 400
        #size_hint: 1, 1
        BoxLayout:
            #padding: 60
            spacing: self.width/100
            orientation: "horizontal"
            pos: 0, root.height - self.height - 10
            #size: 500, 400 
            size_hint_y: None
            Button:
                text: "Ule"
                background_color: (60/255,60/255,60/255,0.5)
                on_press: root.now("ule")
                size_hint_y: None
            Button:
                text: "Alerty"
                background_color: (60/255,60/255,60/255,0.5)
                on_press: root.now('alert')
                size_hint_y: None
                #height: '48dp'
            Button:
                text: "Archiwum"
                background_color: (60/255,60/255,60/255,0.5)
                on_press: root.now('arch')
                size_hint_y: None
                #height: '48dp'
            Button:
                text: "Ustawienia"
                background_color: (60/255,60/255,60/255,0.5)
                on_press: root.now('set')
                size_hint_y: None
                

        
        


<Ule>:
    canvas.before:
        Color:
            rgba: (240/255,201/255,1/255,1)
        Triangle:
            points: [int(2 * root.width), root.height, 0, int(0.9*root.height), 0, root.height]
    Image:
        source: "image/pszola.png"
        pos: root.width - self.width, root.height - self.height
        size: root.width, root.height - 10
    
    ScrollView:
        size: 500, 2*root.height
        pos: root.width - self.width, root.height - self.height - 200
        BoxLayout:
            id: layout
        
            orientation: "vertical"
            pos: root.width -self.width + 10, root.height - self.height - 50
            size: root.width-20, 2*root.height - 100
            size_hint: None, None
            Label:
                text: "Tu bylby ul"
                canvas.before:
                    Color: 
                        rgba: (20/255,20/255,20/255,0.5)
                    Rectangle:
                        pos: self.pos
                        size: self.size
            Label:
                text: "Tu bylby ul"
            Label:
                text: "Tu bylby ul"
            Label:
                text: "Tu bylby ul"
            Label:
                text: "Tu bylby ul"
            Label:
                text: "Tu bylby ul"
            Label:
                text: "Tu bylby ul"
            Label:
                text: "Tu bylby ul"
            Label:
                text: "Tu bylby ul"
            Label:
                text: "Tu bylby ul"
            Label:
                text: "Tu bylby ul"
    Menu:
<Alert>:
    canvas.before:
        Color:
            rgba: (240/255,201/255,1/255,1)
        Triangle:
            points: [int(2 * root.width), root.height, 0, int(0.9*root.height), 0, root.height]
    Image:
        source: "image/pszola.png"
        pos: root.width - self.width, root.height - self.height
        size: root.width, root.height - 10
    BoxLayout:

        id: layout
        
        orientation: "vertical"
        pos: (root.width -self.width)/2, root.height - 1.5*self.height 
        size: 400, 400
        size_hint: None, None

        padding: 60
        spacing: 10
        Label:
            text: "Tu bylyby alerty"
            canvas.before:
                Color: 
                    rgba: (20/255,20/255,20/255,0.5)
                Rectangle:
                    pos: self.pos
                    size: self.size
        Button:
            text: "I są"
            background_color: (60/255,60/255,60/255,0.5)
            on_press: root.idle()
    Menu:
<Notif>:
    canvas.before:
        Color:
            rgba: (240/255,201/255,1/255,1)
        Triangle:
            points: [int(2 * root.width), root.height, 0, int(0.9*root.height), 0, root.height]
    Image:
        source: "image/pszola.png"
        pos: root.width - self.width, root.height - self.height
        size: root.width, root.height - 10
    BoxLayout:

        id: layout
        
        orientation: "vertical"
        pos: (root.width - self.width)/2, int(root.height/4)
        size: 400, 400
        size_hint: None, None
        padding: 60
        spacing: 10
        Label:
            size_hint: 2, 1
            text: "Tu bylyby dzikie wykresy"
            canvas.before:
                Color: 
                    rgba: (20/255,20/255,20/255,0.5)
                Rectangle:
                    pos: self.pos
                    size: self.size
    Menu:    
<Sett>:
    canvas.before:
        Color:
            rgba: (240/255,201/255,1/255,1)
        Triangle:
            points: [int(2 * root.width), root.height, 0, int(0.9*root.height), 0, root.height]

    BoxLayout:

        id: layout
        
        orientation: "horizontal"
        pos: (root.width -self.width)/2, root.height - 2*self.height 
        size: 400, 400
        size_hint: None, None
        padding: 60
        
        Label: 
            text: "Tryb ciemny"
            size_hint: 4,1
            canvas.before:
                Color: 
                    rgba: (20/255,20/255,20/255,0.5)
                Rectangle:
                    pos: self.pos
                    size: self.size
            
        CheckBox: 
            on_active: root.checkbox_click(self, self.active) 
            size_hint: 1,1
            active: True
            canvas.before:
                Color: 
                    rgba: (20/255,20/255,20/255,0.5)
                Rectangle:
                    pos: self.pos
                    size: self.size
    Menu:    


    

    
