#:kivy 1.0
#:import ScreenManager kivy.uix.screenmanager.ScreenManager
#:import FadeTransition kivy.uix.screenmanager.FadeTransition
#:import idle nf.idle




<Menu>:
    FloatLayout:
        #size: 500, 400
        #size_hint: 1, 1
        BoxLayout:
            #padding: 60
            spacing: self.width/100
            orientation: "horizontal"
            pos: 0, root.height - self.height - 10
            #size: 500, 400 
            size_hint_y: None
            Button:
                text: "Ule"
                background_color: (60/255,60/255,60/255,0.5)
                on_press: root.now("ule")
                size_hint_y: None
            Button:
                text: "Alerty"
                background_color: (60/255,60/255,60/255,0.5)
                on_press: root.now('alert')
                size_hint_y: None
                #height: '48dp'
            Button:
                text: "Archiwum"
                background_color: (60/255,60/255,60/255,0.5)
                on_press: root.now('arch')
                size_hint_y: None
                #height: '48dp'
            Button:
                text: "Ustawienia"
                background_color: (60/255,60/255,60/255,0.5)
                on_press: root.now('set')
                size_hint_y: None
                

        
<BazaGrid@GridLayout>:
    cols: 4
    #orientation: "horizontal"
    canvas.before:
        Color: 
            rgba: (20/255,20/255,20/255,0.5)
        Rectangle:
            pos: self.pos
            size: self.size
    Image:
        source: "image/ul.png"
        size_hint: 1, 1
    Label:
        text: "Waga"
    Label:
        text: "Temperatura"
    Label:
        text: "Wilogtność"     


<Ule>:

    
    canvas.before:
        Color:
            rgba: (240/255,201/255,1/255,1)
        Triangle:
            points: [int(2 * root.width), root.height, 0, int(0.9*root.height), 0, root.height]
    Image:
        source: "image/ul.png"
        pos: root.width - self.width, root.height - self.height
        size: root.width, root.height - 10
    
    ScrollView:
        size: 500, 2*root.height
        pos: root.width - self.width, root.height - self.height - 200
        BoxLayout:
            id: layout
        
            orientation: "vertical"
            pos: root.width -self.width + 10, root.height - self.height - 50
            size: root.width-20, 2*root.height - 100
            size_hint: None, None
            spacing: 5
            
            BazaGrid:
                Label:
                    text: root.data
                Label:
                    text: root.waga + "kg"
                Label:
                    text: root.temp +"°C"
                Label:
                    text: root.humi +"%"
            Label:
                text: "Tu bylby ul"
                canvas.before:
                    Color: 
                        rgba: (20/255,20/255,20/255,0.5)
                    Rectangle:
                        pos: self.pos
                        size: self.size
                
            Label:
                text: "Tu bylby ul"
            Label:
                text: "Tu bylby ul"
            Label:
                text: "Tu bylby ul"
    Menu:
<Alert>:
    canvas.before:
        Color:
            rgba: (240/255,201/255,1/255,1)
        Triangle:
            points: [int(2 * root.width), root.height, 0, int(0.9*root.height), 0, root.height]
    Image:
        source: "image/ul_sad.png"
        pos: root.width - self.width, root.height - self.height
        size: root.width, root.height - 10
    BoxLayout:

        id: layout
        
        orientation: "vertical"
        pos: (root.width -self.width)/2, root.height - 1.1*self.height 
        
        size_hint: 1, 0.5

        padding: 60
        spacing: 10
        Label:
            text: "Wszystkie ule są w porządku"
            canvas.before:
                Color: 
                    rgba: (20/255,20/255,20/255,0.5)
                Rectangle:
                    pos: self.pos
                    size: self.size
        Button:
            text: "Sprawdź"
            background_color: (60/255,60/255,60/255,0.5)
            on_press: idle()
    Menu:
<Notif>:
    canvas.before:
        Color:
            rgba: (240/255,201/255,1/255,1)
        Triangle:
            points: [int(2 * root.width), root.height, 0, int(0.9*root.height), 0, root.height]
    Image:
        source: "image/psz.png"
        pos: root.width - self.width, root.height - self.height
        size: root.width, root.height - 10
    BoxLayout:

        id: layout
        
        orientation: "vertical"
        pos: (root.width - self.width)/2, int(root.height/4)
        size: 400, 400
        size_hint: None, None
        padding: 60
        spacing: 10
        Label:
            size_hint: 2, 1
            text: "Tu bylyby dzikie wykresy"
            canvas.before:
                Color: 
                    rgba: (20/255,20/255,20/255,0.5)
                Rectangle:
                    pos: self.pos
                    size: self.size
    Menu:    
<Sett>:
    canvas.before:
        Color:
            rgba: (240/255,201/255,1/255,1)
        Triangle:
            points: [int(2 * root.width), root.height, 0, int(0.9*root.height), 0, root.height]

    BoxLayout:

        id: layout
        spacing: 5
        orientation: "vertical"
        size: root.width, root.height *0.9
        pos: 0, 0
        #pos: (root.width -self.width)/2, root.height - 2*self.height 
        
        size_hint: None, None
        padding: 60
        BoxLayout:
            orientation: "horizontal"
            Label: 
                text: "Tryb ciemny"
                size_hint: 4,1
                canvas.before:
                    Color: 
                        rgba: (20/255,20/255,20/255,0.5)
                    Rectangle:
                        pos: self.pos
                        size: self.size
            
            CheckBox: 
                on_active: root.checkbox_click(self.active) 
                size_hint: 1,1
                active: True
                canvas.before:
                    Color: 
                        rgba: (20/255,20/255,20/255,0.5)
                    Rectangle:
                        pos: self.pos
                        size: self.size
        BoxLayout:
            orientation: "horizontal"
            Label:
                text:"Powiadomienia"
                canvas.before:
                    Color: 
                        rgba: (20/255,20/255,20/255,0.5)
                    Rectangle:
                        pos: self.pos
                        size: self.size
            Button:
                text: "Zarejestruj"
                background_color: (60/255,60/255,60/255,0.5)
            Button:
                text: "Wyrejestruj"
                background_color: (60/255,60/255,60/255,0.5)
    Menu:    


    

    
